### ISSUE TITLE
关于phxsql集群方案

### ISSUE THREAD

**Issue by lhong1001** [Tencent/phxsql#107]
我有个疑问，就是你们给的例子里面的三台机器slave都是备份master上的数据的，也就是说三台机器上的数据都是一样的；这样的话我增加机器也没用呀，因为所有机器上的数据是一样的；我应该怎么做数据分布呢（我的数据在一台机器上是存不下的）？
会不会是这样的，我的猜测：集群中有很多的master，每个master都是2--3个备份，然后我再做一个数据路由的功能把数据分发到各个master，还要做一个查询的功能把请求分发的到各个master，然后把结果在汇集起来返回去？

**Comment by wodesuck** [comment]
可能你对phxsql的功能理解有些偏差，phxsql就是用来保证多台机器上的数据都是一样的。更详细地说，phxsql同步集群中各机数据，并且保证在部分机器宕机或网络分区时，只要集群中有多数派存活就能正常工作。以上是phxsql所做的。

**Comment by larrymeng** [comment]
@lhong1001 的意思是 怎么对mysql进行扩展，使得数据能够分布在不同的mysql集群上。

这个只能是应用层自己做数据的切分。

**Comment by liusifan** [comment]
可以看一下在这个 issue 里面的回复 #110
