### ISSUE TITLE
phxsql 导入数据超级慢

### ISSUE THREAD

**Issue by xrjk** [Tencent/phxsql#112]
通过命令 mysql -uroot -S /tmp/percona.sock  databasename < database.sql 导入数据库，普通mysql机器上10几分钟就好，phxsql要4个多小时，请问哪里配置不对吗

**Comment by wodesuck** [comment]
phxsql集群导入的时候需要同步数据，因此比单机慢是正常现象。可以参考[从现有MySQL数据库迁移](https://github.com/tencent-wechat/phxsql/wiki/%E4%BB%8E%E7%8E%B0%E6%9C%89MySQL%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB)，单机导入后再启动集群。

**Comment by 364137920** [comment]
我65G的数据，导入了16个小时，wodesuck的意思是，先离开集群，导入数据以后，再addmember的意思吗？

**Comment by wodesuck** [comment]
是的
