### ISSUE TITLE
关于PhxSQL修改root密码不成功问题

### ISSUE THREAD

**Issue by 331527583** [Tencent/phxsql#114]
当我将初始的root/空密码修改为root/root之后，数据库始终存在root/root（用户/密码），这是程序本身限定么？如果想将root用户对应密码修改为空时候，会不成功！！！
数据库记录：
select host,user,password from user where user='root' or user='rootroot' \G;
*************************** 1. row ***************************
    host: localhost
    user: root          （将初始密码为空的root用户，修改为root。此后，此条记录不能再修改为空）
password: *81F5E21E35407D884A6CD4A731AEBFB6AF209E1B
*************************** 5. row ***************************
    host: 192.168.56.103
    user: root
password: *81F5E21E35407D884A6CD4A731AEBFB6AF209E1B
*************************** 8. row ***************************
    host: 192.168.56.103
    user: rootroot     （通过root/root账户修改为rootroot/空密码，生成的记录。可以将rootroot/空密码反复修改，但是上条的root/root不能重置为root/空密码）（这是程序限定的吗？？？）
password: 
*************************** 11. row ***************************
    host: localhost
    user: rootroot
password: 
11 rows in set (0.00 sec)

修改root密码命令：
./phxbinlogsvr_tools_phxrpc -f SetMySqlAdminInfo -h 192.168.56.103 -p 17000 -u root -d root -U root -D rootroot   （尝试修改root/root都不能成功）
get master 192.168.56.103 expire time 1493189529
SetMySqlAdminInfo admin username or pwd incorrect

./phxbinlogsvr_tools_phxrpc -f SetMySqlAdminInfo -h 192.168.56.103 -p 17000 -u root -d root -U root -D rootroot    （尝试修改root/root都不能成功）
get master 192.168.56.103 expire time 1493189573
SetMySqlAdminInfo admin username or pwd incorrect

./phxbinlogsvr_tools_phxrpc -f SetMySqlAdminInfo -h 192.168.56.103 -p 17000 -u rootroot -d '' -U root -D root   （只能修改其他非root/root记录）
get master 192.168.56.103 expire time 1493190321
SetMySqlAdminInfo admin username rootroot -> new admin username root

可以帮助下，解答下是什么原因呢？有些困惑，谢谢！！

**Comment by 331527583** [comment]
./phxbinlogsvr_tools_phxrpc -f SetMySqlAdminInfo -h 192.168.56.103 -p 17000 -u rootroot -d '' -U rootroot -D root
get master 192.168.56.103 expire time 1493190860
SetMySqlAdminInfo admin username or pwd incorrect
数据库mysql.user表中已有rootroot/空密码的记录，修改为rootroot/root也不成功。我想我对SetMySqlAdminInfo 的命令-u -d -U -D 使用应该有些误解！！！

**Comment by cjcchen** [comment]
账号是root的时候，是不能设置空密码的。这应该是mysql的限制。
