### ISSUE TITLE
phxsqlproxy_phx use lots of CPU

### ISSUE THREAD

**Issue by tyronecai** [Tencent/phxsql#115]
在CentOS 6.9上用devtools-3的GCC-4.9.2编译最新Release-0.8.5版本(整个编译过程都在干净的docker中按照build.sh完成，因为该gcc版本的ar有问题删掉了percona/storage/tokudb整个目录，其他未做修改)。最终用三个Docker运行phxsql，但安装完毕还未导入数据就发现CPU高，情况同https://github.com/tencent-wechat/phxsql/issues/67 ，在导入数据后出现大量TIME_WAIT连接。

**在宿主机上看到CPU的sys高**，导致4Core的机器Load到了10。（3个Docker一共有6个phxsqlproxy进程）
top - 02:55:48 up 43 days, 19:52,  0 users,  load average: 10.25, 10.50, 10.21
Tasks:   8 total,   1 running,   7 sleeping,   0 stopped,   0 zombie
Cpu0  :  9.1%us, 35.8%sy,  0.0%ni, 54.7%id,  0.0%wa,  0.0%hi,  0.4%si,  0.0%st
Cpu1  : 13.0%us, 50.4%sy,  0.0%ni, 36.2%id,  0.4%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu2  : 11.7%us, 37.7%sy,  0.0%ni, 50.5%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu3  : 10.2%us, 38.5%sy,  0.0%ni, 51.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st

1124 root      20   0 2698m  85m 2520 R 30.5  1.5  25:59.27 /opt/phxsql/sbin/phxsqlprox
 2902 root      20   0 2698m  85m 2476 S 31.4  1.5  24:44.91 /opt/phxsql/sbin/phxsqlprox
 4660 root      20   0 2707m  85m 2468 R 31.4  1.5  24:18.46 /opt/phxsql/sbin/phxsqlprox
 4661 root      20   0 2698m  85m 2468 S 30.5  1.5  24:14.74 /opt/phxsql/sbin/phxsqlprox
 2901 root      20   0 2706m  84m 2476 S 30.5  1.5  24:45.10 /opt/phxsql/sbin/phxsqlprox
 1123 root      20   0 2707m  83m 2520 S 31.4  1.5  18:16.95 /opt/phxsql/sbin/phxsqlprox

**用perf top -p $pid 看到的是**
40.66% [kernel] [k] finish_task_switch
10.81% [kernel] [k] __bpf_prog_run
10.80% [kernel] [k] _raw_spin_unlock_irqrestore
5.21% [kernel] [k] pvclock_clocksource_read
2.68% libc-2.12.so [.] klogctl
2.47% [kernel] [k] kvm_clock_read
2.25% phxsqlproxy_phxrpc [.] 0x0000000000036b93
1.76% [kernel] [k] do_syscall_64
1.50% phxsqlproxy_phxrpc [.] 0x00000000000368a9

**strace -ff -vv -tt -p $pid 看到的都是**epoll_wait以及gettimeofday相关的
[pid 1222] 09:57:38.988238 epoll_wait(51, <unfinished ...>
[pid 1161] 09:57:38.988267 <... gettimeofday resumed> {1493258258, 987848}, NULL) = 0
[pid 1159] 09:57:38.988290 <... gettimeofday resumed> {1493258258, 987830}, NULL) = 0
[pid 1157] 09:57:38.988339 epoll_wait(42, <unfinished ...>
[pid 1152] 09:57:38.988452 <... gettimeofday resumed> {1493258258, 987879}, NULL) = 0
[pid 1150] 09:57:38.988480 <... epoll_wait resumed> {}, 10240, 1) = 0
[pid 1147] 09:57:38.988504 epoll_wait(40, <unfinished ...>
[pid 1145] 09:57:38.988530 <... epoll_wait resumed> {}, 10240, 1) = 0
[pid 1142] 09:57:38.988551 <... epoll_wait resumed> {}, 10240, 1) = 0
[pid 1134] 09:57:38.988576 gettimeofday( <unfinished ...>
[pid 1346] 09:57:38.988651 gettimeofday( <unfinished ...>
[pid 1339] 09:57:38.988676 <... gettimeofday resumed> {1493258258, 988451}, NULL) = 0
[pid 1335] 09:57:38.988700 epoll_wait(94, <unfinished ...>
[pid 1322] 09:57:38.988721 <... gettimeofday resumed> {1493258258, 988417}, NULL) = 0
[pid 1315] 09:57:38.988744 <... epoll_wait resumed> {}, 10240, 1) = 0
[pid 1312] 09:57:38.988767 <... epoll_wait resumed> {}, 10240, 1) = 0

我刚才还怀疑是Docker导致的，现在直接在宿主机上执行完"python install.py"就发现CPU sys高。请问这个可能是什么原因导致的，而且为什么是sys高？

**Comment by tyronecai** [comment]
在CentOS7上同样执行完"python install.py"就发现CPU sys高。

%Cpu0  :  3.2 us, 14.7 sy,  0.0 ni, 82.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  3.1 us, 12.5 sy,  0.0 ni, 84.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  3.2 us,  8.4 sy,  0.0 ni, 88.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  3.1 us,  7.3 sy,  0.0 ni, 89.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st

19817 root      20   0 2698.8m  68.4m   2.5m S  25.0  1.9   0:10.19 /data/phxsql/phxsql/sbin/phxsqlproxy_phxrpc /data/phxsql/phxsql/etc/phxsqlprox+
19816 root      20   0 2707.7m  68.4m   2.5m S  24.0  1.9   0:10.21 /data/phxsql/phxsql/sbin/phxsqlproxy_phxrpc /data/phxsql/phxsql/etc/phxsqlprox+

**Comment by wodesuck** [comment]
有观察过 InitBinlogSvrMaster 之后的情况吗

**Comment by 331527583** [comment]
当对phxsql集群压力测试时候，phxsqlproxy会开辟很多线程，如何回收proxy占用的资源？

**Comment by wodesuck** [comment]
phxsqlproxy.conf里有几个选项，MasterWorkerThread,MasterIORoutineCnt,SlaveWorkerThread,SlaveIORoutineCnt，可以调节线程数和协程数。
