### ISSUE TITLE
请教关于运维方面的两个问题

### ISSUE THREAD

**Issue by zqdai** [Tencent/phxsql#121]
部署phxsql运行几个月以后，发现两个运维方面的问题
1、启动时间过长
从日志看，应该是paxos需要从头replay所有已经确定的instance所致。

2、扩容问题
当把一个新节点加入到集群中时，它需要从头开始同步所有的binlog，这导致扩容所需的时间很长，而且binlog需要永久存储，占用大量空间。

请问有没有办法定期清除binlog和paxos的instances？谢谢！

**Comment by cjcchen** [comment]
phxsql的配置文件中可以配置instance的保留时间，默认是7天。
instance的保留时间变短了，新节点扩容的时候读取的数据就少了。

**Comment by zqdai** [comment]
能否说明一下具体是那个配置项？

我找到了以下几个选项有关，不知道跟这个问题有没有关系？
MaxFileSize=
CheckPointTime=
MaxDeleteCheckPointFileNum=

**Comment by 331527583** [comment]
应该是CheckPointTime,尝试下

**Comment by zqdai** [comment]
解决了，谢谢！！
