### ISSUE TITLE
Is it possible to install the PhxSQL on Windows Server? 

### ISSUE THREAD

**Issue by xmeng1** [Tencent/phxsql#122]
Is it possible to install the PhxSQL on Windows Server? 

I have found that 4 of the 6 third-party libraries (glog, leveldb, protobuf, phxpaxos, colib, phxrpc) support Windows Server: glog, leveldb, protobuf, colib. But I am not sure whether the phxrpc and phxpaxos are supporting on Windows.

**Comment by wodesuck** [comment]
Not support on Windows yet.
