### ISSUE TITLE
切换master问题

### ISSUE THREAD

**Issue by xiaoleib108** [Tencent/phxsql#126]
三台服务器组成集群，手动停止master服务器的phxsqlproxy_phxrpc、phxbinlogsvr、mysql服务，通过phxbinlogsvr_tools_phxrpc -f GetMemberList，查看主已经切换，但是无法写入，查看phxbinlogsvr.ERROR日志，发现错误信息：
E0719 08:55:55.000604 14926 phx_glog.cpp:78]  DoQuery[mysql] mysql_query fail 1, Access denied; you need (at least one of) the SUPER privilege(s) for this operation, command set global server_id=3232262053; 
E0719 08:55:55.000766 14926 phx_glog.cpp:78]  CheckMasterInit master init failed  
E0719 08:55:55.000861 14926 phx_glog.cpp:78]  Process master changeing fail 5002 
通过查询数据库，发现是只读状态：
mysql> show variables like '%read_only%';
+------------------+-------+
| Variable_name    | Value |
+------------------+-------+
| innodb_read_only | OFF   |
| read_only        | ON    |
| super_read_only  | ON    |
| tx_read_only     | OFF   |
+------------------+-------+

**Comment by 331527583** [comment]
你写入的节点，还是原来的节点？这时候，你GetMasterInfoFromGlobal下，看看切换后的master ip是多少，你只能对新master进行写入操作。

**Comment by xiaoleib108** [comment]
你好，三个数据库IP存在数组中，测试程序从数组中取IP，然后进行连接IP的54321端口。如果成功，则插入数据。如果不成功，则会连接下一个IP。手动停掉master的phxsqlproxy_phxrpc、phxbinlogsvr、mysql服务时，会有一段时间在选master，程序尝试插入数据不成功，查看新的master的read_only ON，super_read_only  ON。

**Comment by 331527583** [comment]
选主时间在phxbinlogsvr.conf 下，MasterLease 配置，模板中设定20s。
查看下所有节点的read_only 状态。show global variables like '%read_only%';
master 切换成功，read_only 应该会off

**Comment by xiaoleib108** [comment]
通过phxbinlogsvr_tools_phxrpc -f GetMasterInfoFromGlobal命令查看master已经切换，但是新master的read_only还是off，日志中报错和之前一样（CheckMasterInit master init failed Process master changeing fail 5002）。

**Comment by wodesuck** [comment]
看起来是master去初始化mysql出了问题，麻烦贴一下binlogsvr 5002前的日志

**Comment by xiaoleib108** [comment]
调整了phxbinlogsvr.conf 下，MasterLease 配置的时间，可以减少问题的出现，能否提供关于配置文件中各个参数的说明，谢谢！

**Comment by wodesuck** [comment]
https://github.com/tencent-wechat/phxsql#2-phxbinlogsvrconf
https://github.com/tencent-wechat/phxsql/blob/master/README.zh_cn.md#2-phxbinlogsvrconf
@xiaoleib108 README里面有
