### ISSUE TITLE
[咨询] 是否可以将BINLOG FORMAT设置成ROW模式

### ISSUE THREAD

**Issue by tangxy** [Tencent/phxsql#127]
PHXSQL默认是MIXED模式， 是否有必要将其修改为ROW模式？

**Comment by wodesuck** [comment]
可以的

**Comment by tangxy** [comment]
非常感谢    





研发中心   唐希元（西岭）
地址:成都市青羊区广富路218号G7-D单元9层 邮编: 610091
手机: 18000516329
网址: http://www.lakala.com
邮箱:tangxiyuan@lakala.com
 
发件人： Daniel Zhang
发送时间： 2017-07-21 23:06
收件人： tencent-wechat/phxsql
抄送： tangxy; Author
主题： Re: [tencent-wechat/phxsql] [咨询] 是否可以将BINLOG FORMAT设置成ROW模式 (#127)
可以的
