### ISSUE TITLE
不支持pipelining，在跨Region环境(高延迟)下，几乎不可用?

### ISSUE THREAD

**Issue by alexliu5678** [Tencent/phxsql#130]
1:跨Region场景下phxpaxos几乎不可用，
2:X-Paxos的同Region性能是phxpaxos的100倍以上
3:phxpaxos也是基于multi-Paxos实现的独立库，其架构上采用单Paxos单线程设计

**Comment by lingji** [comment]
@alexliu5678 X-Paxos 只是传说中的东西而已，听听就好，phxpaxos则是现实中的。
