### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by rongxr** [Tencent/phxsql#134]
[ 17%] Built target dbug
make[3]: Entering directory `/app/soft/phxsql/phxsql/percona'
make[3]: Leaving directory `/app/soft/phxsql/phxsql/percona'
[ 18%] Built target mysys_ssl
make[3]: Entering directory `/app/soft/phxsql/phxsql/percona'
make[3]: Leaving directory `/app/soft/phxsql/phxsql/percona'
make[3]: Entering directory `/app/soft/phxsql/phxsql/percona'
Linking CXX executable comp_err
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lzlib
collect2: error: ld returned 1 exit status
make[3]: *** [extra/comp_err] 错误 1
make[3]: Leaving directory `/app/soft/phxsql/phxsql/percona'
make[2]: *** [extra/CMakeFiles/comp_err.dir/all] 错误 2
make[2]: Leaving directory `/app/soft/phxsql/phxsql/percona'
make[1]: *** [all] 错误 2
make[1]: Leaving directory `/app/soft/phxsql/phxsql/percona'
make: *** [mysql] 错误 2

**Comment by wodesuck** [comment]
看起来是缺失依赖，少了zlib

**Comment by rongxr** [comment]
已经解决，因为ld找不到zlib，所以报错，需要创建快链接

a、错误：/usr/bin/ld: 找不到 -lz collect2: error: ld returned 1 exit status，则需要先安装 yum install zlib-devel
b、错误：/usr/bin/ld: cannot find -lzlib，则需要源码安装zlib-1.2.11.tar.gz
tar -zxvf zlib-1.2.11.tar.gz
cd zlib-1.2.11
./configure --prefix=/usr/local/zlib && make && make install
ld -lzlib --verbose	#因为ld找不到zlib，所以报错，需要创建快链接
ln -s /usr/local/zlib/lib/libz.so /lib64/libzlib.so
ln -s /usr/local/zlib/lib/libz.a /lib64/libzlib.a

**Comment by taohex** [comment]
这是Percona Server有个地方把`-lz`写成了`-lzlib`导致的，需要手动把现有的`libz.so`和`libz.a`链接成`libzlib.so`和`libzlib.a`。不需要下载zlib源代码的。

**Comment by rongxr** [comment]
因为系统没找到libzlib.so和libzlib.a，所以重装了下

**Comment by taohex** [comment]
是没有这两个文件的
