### ISSUE TITLE
是否提供centOS版的phxsql 0.8.5?

### ISSUE THREAD

**Issue by lukechen72** [Tencent/phxsql#136]
由于未能成功编译源码，能否提供在CentOS上运行的二进制版phxsql0.8.5下载? 由于项目比较急，想跳过编译，直接安装运行phxsql.多谢！

**Comment by wodesuck** [comment]
我这边手头上也没有CentOS的机器，你可以试试ubuntu版的二进制能不能在CentOS上跑起来

**Comment by loveleon** [comment]
我在centos7 gcc4.8.5上编译通过phxsql包。如果需要可以提供给你。我自己使用的是ubuntu。tx内部使用的也是ubuntu平台么？

**Comment by wodesuck** [comment]
tx有内部维护的内核版本，开源的phxsql版本在ubuntu下测试。

**Comment by ZHRichardson** [comment]
> 我在centos7 gcc4.8.5上编译通过phxsql包。如果需要可以提供给你。我自己使用的是ubuntu。tx内部使用的也是ubuntu平台么？

给我发一份rjzou@qq.com谢谢
