### ISSUE TITLE
新建集群无法写入

### ISSUE THREAD

**Issue by lukechen72** [Tencent/phxsql#142]
新建3台机器的集群，设一台为主xx.249，试着用client端mysql连接主，并创建一个表（写入），但不成功，mysql界面显示是无反应，后端日志如下，不知道这个集群创建是否正常，帮看看，多谢
E0920 14:41:25.613293  1728 phx_glog.cpp:78] UpdateMasterStatus:103 GetMaster success but (10.100.19.249:1505889682) expired
E0920 14:41:25.613420  1728 phx_glog.cpp:78] UpdateMasterStatus ret -104
E0920 14:41:25.716527  1728 phx_glog.cpp:78] UpdateMasterStatus:103 GetMaster success but (10.100.19.249:1505889682) expired
E0920 14:41:25.717090  1728 phx_glog.cpp:78] UpdateMasterStatus ret -104
E0920 14:41:25.820490  1728 phx_glog.cpp:78] UpdateMasterStatus:103 GetMaster success but (10.100.19.249:1505889682) expired
E0920 14:41:25.820577  1728 phx_glog.cpp:78] UpdateMasterStatus ret -104
I0920 14:41:25.922652  1728 phx_glog.cpp:86] ERROR: httpcall( /phxbinlogsvr/GetMasterInfoFromGlobal ) -1003
E0920 14:41:25.922673  1728 phx_glog.cpp:78]  client call fail, ret -1003 
E0920 14:41:25.922731  1728 phx_glog.cpp:78] UpdateMasterStatus:82 GetMaster failed ret -1003
E0920 14:41:25.922890  1728 phx_glog.cpp:78] UpdateMasterStatus ret -85
W0920 14:41:38.420181  1749 phx_glog.cpp:74] run: 0 IORoutine is working....
W0920 14:41:38.421568  1757 phx_glog.cpp:74] run: 0 IORoutine is working....
W0920 14:41:38.421651  1786 phx_glog.cpp:74] run: 0 IORoutine is working....
W0920 14:41:38.424932  1775 phx_glog.cpp:74] run

**Comment by wodesuck** [comment]
看上去是不正常的，没有一个合法的 master，检查一下网络是否有问题。

**Comment by lukechen72** [comment]
多谢！
我用TELNET和WGET测了一下，三台机器的端口（设为17000），都是通的； 防火墙也都关闭了，不清楚是啥问题。
在安装的时候，有报警告如下，不知是否这个问题影响连通？
WARNING: The host 'host-10-100-19-249' could not be looked up with /home/yanfa/phxsql/percona.src/bin/resolveip.
This probably means that your libc libraries are not 100 % compatible
with this binary MySQL version. The MySQL daemon, mysqld, should work
normally with the exception that host name resolving will not work.
This means that you should use IP addresses instead of hostnames
when specifying MySQL privileges !
