### ISSUE TITLE
执行install.py程序phxbinlogsvr没有启动

### ISSUE THREAD

**Issue by Freyayan** [Tencent/phxsql#72]
你好，
     我今天在一台机上安装phxsql时候，发现如下报错：
执行完install.py后，发现phxbinlogsvr程序没有启动，其他ok，于是执行如下命令
nohup /cache1/phxsql/sbin/phxbinlogsvr_phxrpc &
报错
phxbinlogsvr_phxrpc: options.cpp:81: void phxpaxos::NodeInfo::MakeNodeID(): Assertion `iIP != (uint32_t)-1' failed.
set bind ip  port 17000
 
请问这个是什么问题？
 
log中仅有的报错：

2016-11-07 16:35:27 36918 [ERROR] Can't open shared library '/cache1/phxsql/lib/phxsync_master_phxrpc.so' (errno: 0 /cache1/phxsql/li
b/phxsync_master_phxrpc.so: undefined symbol: _ZN12phxbinlogsvr15PhxBinlogClient10SendBinLogERKSsS2_)

 
查看了一下，'/cache1/phxsql/lib/phxsync_master_phxrpc.so' 是存在的。。。

**Comment by wodesuck** [comment]
请检查phxbinlogsvr.conf里有没有配置好ip。

phxsync_master_phxrpc.so的错误是编译问题，缺少了符号，可以看一下编译过程又没有什么问题。

**Comment by Freyayan** [comment]
你好，检查phxbinlogsvr.conf里是有ip的，这个错误在其他ip段的机器上没出现，但是在这个ip段这个进程一直无法启动。
[Server]
LogLevel = 3
IP = 180.101.24.55
LogMaxSize = 1600
LogFilePath = /cache1/phxdata/log
Port = 17000

**Comment by Freyayan** [comment]
请问这个问题有谁遇到过吗？  难道还是编译有问题？   不过这个错误我在其他机器安装并没有遇到过哦

**Comment by wodesuck** [comment]
只有一台机出问题？检查一下他们环境有什么差异，看起来是binlogsvr没读到配置。

另外，从你的日志可以看出MySQL插件加载失败，应该编译还有问题，请看一下另外几台机的插件加载情况（本地MySQL里show plugins看有没有rpl_phx_sync_master）。

**Comment by Freyayan** [comment]
谢谢，我重新编译后，在编译环境没有报错的情况下，安装没出先问题了。
