### ISSUE TITLE
question:phxbinlog传输机制

### ISSUE THREAD

**Issue by Freyayan** [Tencent/phxsql#78]
1.目录下的eventdata记录的是什么？
-rwxrwxrwx 1 root root 10491041 Nov 11 11:05 EVENTDATA-717
-rwxrwxrwx 1 root root 10491055 Nov 11 11:06 EVENTDATA-738
-rwxrwxrwx 1 root root 10491058 Nov 11 11:06 EVENTDATA-759
-rwxrwxrwx 1 root root 10491052 Nov 11 11:06 EVENTDATA-780
-rwxrwxrwx 1 root root 10491052 Nov 11 11:06 EVENTDATA-801

2.这条日志能详细解释一下吗？
2016-11-11 11:05:33 45302 [Note]  repl_phx_report_binlog_to_binlogsvr:169 send binlog use 155 ms, max gtid 10ac96f8-a7b0-11e6-9852-001b21b92df0:32 binlog gtid 10ac96f8-a7b0-11e6-9852-001b21b92df0:31

有没有相关的文档解释binlog的传输机制？包括传输速度，同步速度等测试？？

**Comment by cjcchen** [comment]
1. eventdata目录下的文件记录的是binlogsvr的数据。里面包括MySQL的Binlog数据和master信息等。
2. 该日志表示的是MySQL向Binlogsvr提交Binlog，其中包含Binlog的Gtid和提交该数据所花费的时间
3. 相关文档可查看github上的Wiki
