### ISSUE TITLE
期待支持 Docker 

### ISSUE THREAD

**Issue by toontong** [Tencent/phxsql#8]
太难编译~

**Comment by cjcchen** [comment]
http://chuzhiyan.com/2016/09/01/%E5%AE%89%E8%A3%85-PhxSQL-%E7%AC%94%E8%AE%B0/
可以参考下改文档。谢谢

2016-09-01 10:42 GMT+08:00 Huang ChuanTong <notifications@github.com>:

**Comment by toontong** [comment]
https://github.com/toontong/phxsql/blob/master/docker/Dockerfile
懂看dockerfile的，就知道编译不容易。

**Comment by wodesuck** [comment]
[docker镜像](https://hub.docker.com/r/phxsql/phxsql/)和[相关文档](https://github.com/tencent-wechat/phxsql/wiki/Quick-Start-with-Docker)已添加，欢迎食用。
