### ISSUE TITLE
phxbinlog的replication线程的bug

### ISSUE THREAD

**Issue by weipatty** [Tencent/phxsql#89]
bug说明(前提条件)

mysql在超过slave_net_timeout(默认一小时)没进行数据更新时,超过这个时间mysql会认为连接已经断开而重连.

而看了phxbinlog replication 的实现,是只允许一个连接来拉binlog的，因为binlog events的检验依赖于上一条event，串行化累加校验

所以在一个连接开始之前会清空之前全部的连接 而且在一个连接退出时也会清空之前保存的连接(这个我在想有必要清么？开始前保证也许就可以了)。

void *ReplicationManager::SlaveManager(void *arg)
{
  //...
  //这句有必要吗?
  manager->ClearImpl();
	//而且里面impl会调用ctx->close,里面又会调notify进行init初始化 这会导致有问题（见后面bug描述)
}

void ReplicationCtx::Close() {
	CloseMasterFD();
	CloseSlaveFD();
	Notify();//设init
}

slave_net_timeout参数说明
http://dev.mysql.com/doc/refman/5.7/en/replication-options-slave.html#option_mysqld_slave-net-timeout

bug描述(理论分析，但逻辑我觉得应该是对的。。):

1.假设时间为 13:00 ，连接A 一直跑是正常的 ，此时只有一个线程ReplicationTransfer ，是可以保证串行化的 。
2.然后一直没数据更新 到了14:00(slave_net_timeout时间到) 线程A一直阻塞在等events的信号 ，而此时mysql以线程B重连close了线程A的fd，同样也阻塞在等events的信号
3. 这时其实可以过无数个小时，第N个线程重连过来，与前N-1个线程都阻塞在等evnets的信号.但N-1个线程其实已经关了，
4.这时假设14:20分， 数据更新了有event写入,唤醒全部线程 ，唤醒后检测fd是否-1 其它已关闭的线程会退出，而第N个线程会进行事件重读。
5.但此时，由于线程退出时也会清空所有连接，这时正常的线程B会被close掉。那边B在读出事件发送时会报错，然后退出
6.mysql报2013连接丢失错，进行重连，假设为线程C，这里有一个线程调度的先后问题及FD赋值先后的问题： 
 调度：
   B 读事件 -> B Close -> mysql 重连(C) -> C线程起(清impl list,但其实已经空了) -> c run (加入impl list) -> (关键) 调度线程B退出清impl list,这时又把C清掉了 (但其实没清,因为C的FD还没初始化，却意外把C的init赋值了)
 
 FD赋值时机:
    1.先清impl list
    2.将自己加入 impl list
    3.设置FD
    4.RUN
   
如上 
   线程C跑如上流程
    1.先清impl list
    2.将自己加入 impl list
    3.发生线程切换
    4.线程b干掉C,但其实没干掉，这样C就变成了幽灵线程，而且还没等slave ok就读event了
    5.如果一直没有再发生slave_net_timeout内没数据更新由C一直幽灵处理应该是没问题的，但只要再来一次，那么就会有两条线程在读event，将不能保证校验的串行性
       此时 线程C是无效的(由mysql关闭)，这里又涉及一个线程调度的问题,如果一直由后面的线程D读到事件，那么是没问题的. 
       一旦由幽灵线程C读到，，那么就会有问题 可能会有若干个场景，我这里说实际遇到的一个场景是 C读了39事件，报错终于退出了，而D读到40事件，而此时checksum是38的，跳过了40报校验错
     
     
   以上是我理的逻辑，两个问题吧：
   1.线程退出时也clear impl list 导致了幽灵线程
   2.ctx的close 为啥调用notify?导致退出时的close将幽灵线程的init设为true了  
    

复现的两个条件
1.幽灵线程的产生
2.幽灵线程读到事件
这两个都依赖于线程调度。

**Comment by weipatty** [comment]
https://github.com/tencent-wechat/phxsql/issues/59

这里有之前一次的log 
E1028 09:32:20.157697 6710 phx_glog.cpp:82] GetEvents no data 
E1028 09:32:20.157699 27130 phx_glog.cpp:82] GetEvents no data 
有两个线程 6710 27130 同时在读

**Comment by cjcchen** [comment]
该问题已经在fix。谢谢反馈
